### ISSUE TITLE
How to test a new WSDL ?

### ISSUE THREAD

**Issue by camilonova** [gtaylor/python-fedex#39]
Hi there, I'm having issues using ```ShipService_v13.wsdl``` and I want to test the v15. I did replaced the content in these files:

- ```fedex/wsdl/ShipService_v13.wsdl```
- ```fedex/wsdl/test_server_wsdl/ShipService_v13.wsdl```

But is not taking any changes I make, how can I test a different WSDL file ?

**Comment by gtaylor** [comment]
Best bet is to drop some altogether new files in there (don't replace v13) and adjust the names here:

https://github.com/gtaylor/python-fedex/blob/master/fedex/services/ship_service.py
