### ISSUE TITLE
Addition of service to test FedEx Service Availablity 

### ISSUE THREAD

**Issue by yomr** [gtaylor/python-fedex#40]
Can you add another service for checking fedex service availability? This is exposed as an independent service by FedEx

**Comment by gtaylor** [comment]
I don't actively use python-fedex, so if you are asking me specifically, I won't be doing much of anything further until/unless I start using it again. I will, however, gladly review and accept pull requests that come with unit tests.

**Comment by yomr** [comment]
Hey, I will submit a pull request for this. But there is one thing that I am stuck at. In the method _assemble_and_send_request, you use something like 'client.service.track(..)' or client.service.deleteShipment(...). So where are these methods(track, deleteShipment,getRates etc) defined?

**Comment by gtaylor** [comment]
Sorry for the very delayed response.

These are defined in the SOAP WSDL, if I recall correctly.

**Comment by nathanielstenzel** [comment]
Was any progress made on this?

**Comment by yomr** [comment]
Well I didn't use this library as is. I modified a lot of stuff to suit my case. So couldn't submit a patch as such!

**Comment by nathanielstenzel** [comment]
It looks like something was added in January.

https://github.com/python-fedex-devs/python-fedex/blob/889c6e03d1605b9a894e9429ccf44c7f5d9c2f77/fedex/services/availability_commitment_service.py

**Comment by nathanielstenzel** [comment]
Well, I have my solution now.
