### ISSUE TITLE
CustomsValue

### ISSUE THREAD

**Issue by embedded1** [gtaylor/python-fedex#42]
Is it possible to set the CustomsValue attributes?
I would like to add contents value and currency to get the declared_value surcharge rate.

**Comment by prakashpp** [comment]
@embedded1 yes you can add CustomsValue attributes. Have a look at this code: https://github.com/fulfilio/trytond-shipping-fedex/blob/develop/stock.py#L347-L398. Hope this helps!

**Comment by embedded1** [comment]
Thanks!, do you know what are the required fields to get the declared value surcharge?

**Comment by gtaylor** [comment]
Looks like this got answered, so I'll go on ahead and close this.
