### ISSUE TITLE
RequestedShipment: suds build error

### ISSUE THREAD

**Issue by embedded1** [gtaylor/python-fedex#43]
I don't know what went wrong but I got everything working last night and now I receive this weird suds build error:

        An error occured while building a instance of (RequestedShipment).  As a result
        the object you requested could not be constructed.  It is recommended
        that you construct the type manually using a Suds object.
        Please open a ticket with a description of this error.
        Reason: Type not found: '(CommercfDutiesPaymentialInvoiceDetail, http://fedex.com/ws/rate/v16, )'

I've tried to reinstall the fedex library but still no luck.
Does anyone know how to solve this error?

**Comment by radlws** [comment]
What version of python and suds are you using?

**Comment by radlws** [comment]
There is no type `CommercfDutiesPaymentialInvoiceDetail` in the wsdl. This issue can be closed.

**Comment by radlws** [comment]
Looking at https://pypi.python.org/pypi/suds-jurko, so this will be the new soap/wsdl client to use in the near future.
