### ISSUE TITLE
Doesn't support Python3

### ISSUE THREAD

**Issue by rajatkhanduja** [gtaylor/python-fedex#55]
Unable to install the library using pip3.

**Comment by radlws** [comment]
Hello,

Once I am able to maintain the package, I will be updating the dependency on suds which lacks python 3 support. SUDS-jurko is an active Python 2/3 project that was released on 11/2013. I have already tried this package out on my local fork and with a few minor tweaks to the base request and samples, I was able to get it working.

So its coming soon, thanks
Rad

**Comment by radlws** [comment]
I just created a PR for this, and and tested everything with both python 2 and 3.  So python 3 will be supported in next release. Cheers

**Comment by gtaylor** [comment]
Merged #56

**Comment by gtaylor** [comment]
Merged #56

**Comment by radlws** [comment]
its working now

`
$ echo '-e git://github.com/gtaylor/python-fedex.git#egg=python-fedex' > r.txt
$ sudo pip3 install -r r.txt

The directory '/Users/rad/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/rad/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Obtaining python-fedex from git+git://github.com/gtaylor/python-fedex.git#egg=python-fedex (from -r r.txt (line 1))
  Updating ./src/python-fedex clone
Collecting suds-jurko (from python-fedex->-r r.txt (line 1))
  Downloading suds-jurko-0.6.tar.bz2 (143kB)
    100% |████████████████████████████████| 147kB 2.5MB/s
Installing collected packages: suds-jurko, python-fedex
  Running setup.py install for suds-jurko
  Running setup.py develop for python-fedex
Successfully installed python-fedex suds-jurko-0.6
`

**Comment by rajatkhanduja** [comment]
That was quite prompt! Thanks.
