### ISSUE TITLE
This lib not support MPS , so how can we manage it

### ISSUE THREAD

**Issue by K-PRAKASH** [gtaylor/python-fedex#57]
Well friends i an using it, and facing a scenario/problem  
A customer XYZ want to make purchase from my e-commerce site
his cart have 3 different item (weight of  60,70 and 70 lb lb)
Now as FedEx have some weight restriction like 150 lb is the max weight for a package 

So how can i deliver him 200 lb
Now i need to use MPS
https://www.fedex.com/us/developer/WebHelp/ws/2014/dvg/WS_DVG_WebHelp/14_4_1_Multiple_Piece_Shipment_Request_Elements.htm

Please help me,
waiting for your response!

**Comment by radlws** [comment]
This is possible, you can create an additional `RequestedPackageLineItem` (see the create_shipment.py example). When done use `add_package` function to add the package to RequestedPackageLineItems. The package count will be automatically incremented.

**Comment by K-PRAKASH** [comment]
Tanks for you quick response!
Yes you are right , i have tested it with FedEx Ground and FedEx Home Delivery 
using the  first tracking reference as master tracking reference 
(
shipment.RequestedShipment.MasterTrackingId.TrackingIdType='FEDEX'
shipment.RequestedShipment.MasterTrackingId.TrackingNumber=XXXXXXX(first_tracking_ref)
)
and it working fine.

but expect of these two service
 it always showing the "Rating Service temporally not available " for all other service(like PRIORITY_OVERNIGHT,STANDARD_OVERNIGHT,FEDEX_EXPRESS_SAVER etc.)
on the same time i am getting the shipment rate for these service on the same zipcode and credentials using the concept of single shipment.
 

It's will be very thanks full if you  will share one example of
#FedEx(MPS)  for service like PRIORITY_OVERNIGHT or any other (except Ground Services)
#FedEx(NTERNATIONAL) like(INTERNATIONAL_ECONOMY,INTERNATIONAL_FIRST or any other )


Thanks in advance for sharing
 such a well manage  python FedEx Library and helping in promoting the Open-source culture  :+1: !

**Comment by radzhome** [comment]
I believe this may be a known issue when using sandbox credentials, see the discussion: http://stackoverflow.com/questions/11156258/rating-is-temporarily-unavailable-error-in-fedex

**Comment by K-PRAKASH** [comment]
Well thanks for your answer . 
I would like to request  you that please , please also include a example of International Shipping ,
Merry Christmas to you my friend  .
I am waiting   for new updates in the example folders ,

**Comment by vishal-manani** [comment]
I am also facing the same problem could you please send me code or add_package code?
